@dl_server_url = {{$dotenv DL_SERVER}}
@dl_server_port = {{$dotenv DL_PORT}}
@dl_apiKey = {{$dotenv DL_API_KEY}}

@epcis_server_url = {{$dotenv EPCIS_SERVER}}
@epcis_server_port = {{$dotenv EPCIS_PORT}}
@epcis_apiKey = {{$dotenv EPCIS_API_KEY}}

@webvoc_server_url = {{$dotenv WEBVOC_SERVER}}
@webvoc_server_port = {{$dotenv WEBVOC_PORT}}
@webvoc_apiKey = {{$dotenv WEBVOC_API_KEY}}

@keyType = 01
@linkTypeValue = gs1:masterData
@idValue = urn:epc:id:sscc:08600031303.0003

### Health Check
GET {{dl_server_url}}:{{dl_server_port}}/health


### Create Digital Links (Bulk Format)
POST {{dl_server_url}}:{{dl_server_port}}/digitallink/new
Content-Type: application/json
X-API-Key: {{dl_apiKey}}

{
  "anchor": "/417/8800026900078",
  "itemDescription": "Oliot dl resolver for dl",
  "defaultLinktype": "gs1:epcis",
  "links": [
    {
      "linktype": "gs1:epcis",
      "href": "http://{{epcis_server_url}}:{{epcis_server_port}}/epcis/v2",
      "title": "Oliot EPCIS Server",
      "type": "application/json",
      "hreflang": [
        "en"
      ]
    }
  ]
}


### Resolve Digital Link
GET {{dl_server_url}}:{{dl_server_port}}/digitallink/417/8800026900078?linkType=gs1:epcis
Accept: application/json
X-API-Key: {{dl_apiKey}}

### Delete Digital Link
DELETE  {{dl_server_url}}:{{dl_server_port}}/digitallink/417/8800026900078?linkType=gs1:epcis
Accept: application/json
X-API-Key: {{dl_apiKey}}